### ISSUE TITLE
Stop relying setting RemoveSelfLink=false feature-gate - we're locking it to true with GA graduation in 1.24

### ISSUE THREAD

**Issue by wojtek-t** [giantswarm/giantnetes-terraform#543]
Upstream Kubernetes is going to get rid of ability to set SelfLink in release 1.24 (basically graduate graduate RemoveSelfLink feature gate to stable - see the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink, for a bit more details).

It seems that microk8s is still relying on setting it to false in two places:
https://github.com/giantswarm/giantnetes-terraform/blob/master/templates/files/manifests/api-server.yaml#L56

This is one more heads'up to stop relying on it.

**Comment by whites11** [comment]
Hi @wojtek-t 
Thanks for this issue and sorry I didn't notice it before.
For my understanding, are you using this project for something?
I'm asking because this is a very giantswarm-specific project and I didn't really expect anyone using it

**Comment by wojtek-t** [comment]
Hi,
 No - I'm not using this project - I was just looking from github to see if there are projects that our deprecation may potentially break and notifying them.

**Comment by whites11** [comment]
That makes a lot of sense, thank you very much then, appreciated <3
